server:
  port: 8081
spring:
  application:
    name: taskswift
  datasource:
    url: jdbc:postgresql://ts-database-v1.cj48agmumj7n.ap-southeast-1.rds.amazonaws.com:5432/taskswift
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.taskswift@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com