server:
  port: 8081
spring:
  config:
    import: optional:secrets.properties
  datasource:
    url: jdbc:postgresql://database-1.cj48agmumj7n.ap-southeast-1.rds.amazonaws.com:5432/TaskSwiftDatabase
    username: postgres
    password: ${AWS_MASTER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.taskswift@gmail.com
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com